server.port=8084

spring.data.mongodb.uri=mongodb+srv://ashandhanushka16_db_user:mashi123@cluster0.bqtbclw.mongodb.net/appointments_db?appName=Cluster0

# Universal Kafka Server
spring.kafka.bootstrap-servers=localhost:9092

# Producer Specifics
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Mapping for the Appointment Event
spring.kafka.producer.properties.spring.json.type.mapping=appointment:edu.uok.stu.dto.AppointmentEvent