server.port=8083

spring.data.mongodb.uri=mongodb+srv://ashandhanushka:Mashi123@tablex.q2ab2lu.mongodb.net/TableX_db?retryWrites=true&w=majority

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ashandhanushka16@gmail.com
spring.mail.password=dbil haeu bsfg dzrs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

# JSON Deserializer Settings
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Type Mapping (Crucial: Matches your actual DTO package)
spring.kafka.consumer.properties.spring.json.type.mapping=notification:edu.uok.stu.model.dto.CreateNotificationRequest

